#!/usr/bin/env python3
import os
import subprocess
import argparse
import math
import re

# configuration
OUTPUT_DIR = "./.."
MUDIRAC_EXEC = "mudirac" 
SHELL_MAP = {
    1: 'K', 2: 'L', 3: 'M', 4: 'N', 5: 'O', 
    6: 'P', 7: 'Q', 8: 'R', 9: 'S', 10: 'T',
    11: 'U', 12: 'V', 13: 'W', 14: 'X'
}
# helpers

def get_quantum_numbers(k):
    '''
    Index k mapping: 1->s1/2, 2->p1/2, 3->p3/2, 4->d3/2, 5->d5/2, etc.
    '''
    if k == 1:
        return 0, 0.5 # s1/2: l=0, j=1/2
    elif k % 2 == 0:
        l = k // 2
        return l, l - 0.5 # e.g., k=2 -> l=1, j=1/2
    else:
        l = (k - 1) // 2
        return l, l + 0.5 # e.g., k=3 -> l=1, j=3/2

def get_transitions(n_initial, n_final):
    si = SHELL_MAP.get(n_initial)
    sf = SHELL_MAP.get(n_final)
    if not si or not sf: return []
    
    lines = []
    
    # Calculate max subshell index for a given n
    # Max index = 2*n - 1
    max_k_initial = 2 * n_initial - 1
    max_k_final = 2 * n_final - 1
    for ki in range(1, max_k_initial + 1):
        li, ji = get_quantum_numbers(ki)
        for kf in range(1, max_k_final + 1):
            lf, jf = get_quantum_numbers(kf)
            # Rule 1: Delta l must be exactly 1 (parity change)
            delta_l = abs(li - lf)
            if delta_l != 1:
                continue    
            # Rule 2: Delta j must be 0 or 1
            delta_j = abs(ji - jf)
            if delta_j > 1.001: # Use small epsilon for float comparison
                continue
            lines.append(f"{sf}{kf}-{si}{ki}")

    return lines

def get_mudirac_default_c_au(element, isotope):
    dummy_base = f"dummy_{element}_{isotope}"
    dummy_in = f"{dummy_base}.in"
    dummy_log = f"{dummy_base}.log"
    dummy_spec = f"{dummy_base}.spec.dat"

    with open(dummy_in, "w") as f:
        f.write(f"element: {element}\n")
        f.write(f"isotope: {isotope}\n")
        f.write(f"xr_lines: L2-K1\n")
        f.write(f"nuclear_model: FERMI2\n")
        f.write(f"electronic_config: {element}\n")
    
    try:
        subprocess.run([MUDIRAC_EXEC, dummy_in], check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        if not os.path.exists(dummy_log):
            raise FileNotFoundError(f"Log file {dummy_log} was not generated by MuDirac.")
        with open(dummy_log, "r") as f:
            output = f.read()
        match = re.search(r"Initial.*Coulomb\s+Fermi-2\s+potential,\s*c\s*=\s*([0-9]*\.?[0-9]+(?:[eE][+-]?[0-9]+)?)", output, re.IGNORECASE)
        if match:
            return float(match.group(1))
        else:
            raise RuntimeError(f"Could not find 'c = ...' in {dummy_log}.")
            
    finally:
        if os.path.exists(dummy_in): os.remove(dummy_in)
        if os.path.exists(dummy_log): os.remove(dummy_log)
        if os.path.exists(dummy_spec): os.remove(dummy_spec)

def calc_excited_fermi_c_au(c_gs_au, delta_r2_fm2):
    """
    根据基态的 c (a.u.) 和 delta r^2 (fm^2) 计算激发态的 c (a.u.)
    公式推导: c_m^2 = c_gs^2 + (5/3)*delta_r^2
    """
    FM_TO_AU = 1.889726125e-5
    AU_TO_FM = 1.0 / FM_TO_AU
    c_gs_fm = c_gs_au * AU_TO_FM

    c_m_fm_sq = (c_gs_fm ** 2) + (5.0 / 3.0) * delta_r2_fm2
    
    if c_m_fm_sq <= 0:
        raise ValueError("Invalid delta_r2: resulted in negative c^2.")
        
    c_m_fm = math.sqrt(c_m_fm_sq)
    return c_m_fm * FM_TO_AU

# main
def run(args):
    ELEMENT = args.element
    Z = args.atomic_number
    ISOTOPE = args.isotope
    MAX_N = args.max_n

    SUFFIX = ""
    fermi_c_au = None

    if not os.path.exists(OUTPUT_DIR):
        os.makedirs(OUTPUT_DIR)


    if args.delta_r2 is not None:
        print(f"[INFO] Excited state mode enabled (Delta r^2 = {args.delta_r2} fm^2).")
        print(f"       Running dummy job to extract MuDirac's default ground state 'c'...")
        c_gs_au = get_mudirac_default_c_au(ELEMENT, ISOTOPE)
        print(f"       -> Extracted ground state c = {c_gs_au:.8e} a.u.")
        fermi_c_au = calc_excited_fermi_c_au(c_gs_au, args.delta_r2)
        SUFFIX = "m"
        print(f"       -> Calculated excited state c = {fermi_c_au:.8e} a.u.")
        print(f"       Suffix 'm' will be automatically added to outputs.")
    else:
        print(f"[INFO] Ground state mode enabled. MuDirac will use internal default nuclear parameters.")

    for ni in range(2, MAX_N + 1): 
        for nf in range(1, ni):      
            lines = get_transitions(ni, nf)
            if not lines:
                continue
            lines_str = ",".join(lines)
            
            job_name = f"{ELEMENT}{ISOTOPE}{SUFFIX}_N{ni}_to_N{nf}"
            in_file = f"{job_name}.in"

            with open(in_file, "w") as f:
                f.write(f"element: {ELEMENT}\n")
                f.write(f"isotope: {ISOTOPE}\n")
                f.write(f"xr_lines: {lines_str}\n")
                f.write(f"write_spec: T\n") 
                f.write(f"nuclear_model: FERMI2\n")
                if fermi_c_au is not None:
                    f.write(f"fermi_c: {fermi_c_au:.8e}\n")  
                f.write(f"electronic_config: {ELEMENT}\n")
                f.write(f"uehling_correction: T\n")
            
            print(f"Running {job_name} [Lines: {lines_str}] ...")
            
            try:
                subprocess.run([MUDIRAC_EXEC, in_file], check=True, stdout=subprocess.DEVNULL)
                generated_spec = f"{job_name}.spec.dat"
                if os.path.exists(generated_spec):
                    target_name = f"Z{Z}_A{ISOTOPE}{SUFFIX}_Ni{ni}_Nf{nf}.dat"
                    target_path = os.path.join(OUTPUT_DIR, target_name)
                    os.rename(generated_spec, target_path)
                    print(f" -> Saved to {target_path}")
                else:
                    print(f" -> Error: Output file {generated_spec} not found.")

            except Exception as e:
                print(f" -> Failed: {e}")

# args
def main():
    parser = argparse.ArgumentParser(description="Generate MuDirac input files and run simulations.")
    parser.add_argument("-e", "--element", type=str,  help="Element symbol (example: Th)", required=True)
    parser.add_argument("-z", "--atomic_number", type=int, help="Atomic number ", required=True)
    parser.add_argument("-a", "--isotope", type=int, help="Isotope mass number ", required=True)
    parser.add_argument("-n", "--max_n", type=int, help="Maximum principal quantum number", required=True)
    parser.add_argument("--delta_r2", type=float, default=None, 
                        help="Delta <r^2> in fm^2. If provided, calculates excited state fermi_c and automatically appends 'm' suffix.")
    args = parser.parse_args()
    run(args)
    
if __name__ == "__main__":
    main()
